Quatro Tetris - Updated Executables, Updated Info Files, Updated Game Versions - Updated Executable to detect and show an specific error when a SyntaxError is detected, Added errors 0004 & 0005 to error list, Created an errortest game version to text error comprehension.

diff --git a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
--- a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
+++ b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
@@ -1,7 +1,6 @@
 #!/bin/bash
 # Tells the user what part of this file is running
 echo "Checking Requirements..."
-sleep 1 # Adds fake delay to increase the amount of time the text shows
 
 # Sets the modules required for the program to be ran
 modules=("pygame" "random" "time" "easing" "soundmanager" "configparser")
@@ -17,16 +16,8 @@ for module in "${modules[@]}"; do
     fi
 done
 
-# Clears the screen because the process was finished
-clear
-
 # Prompts the user for what version of Quatro Tetris they want to run
-read -p "Enter the Python version number to run (e.g., v0.0.1, v0.0.2): " version
-clear
-
-# Tells the user what part of this file is running
-echo "Checking python version..."
-sleep 1 # Adds fake delay to increase the amount of time the text shows
+read -p "Enter the Python version number to run (e.g., v0.0.1, v0.0.2): " quatro_version
 
 # Detects the type of python command you have installed on your system
 if command -v python &>/dev/null; then # Checks to see if you use 'python'
@@ -52,24 +43,11 @@ else
     echo "It appears that you do not have a valid Python 3 command interpreter. Quatro Tetris cannot be run without Python 3. Please install a Python 3 Interpreter and try again."
 fi
 
-# Clears the screen because the process was finished
-clear
-
-# Tells the user what part of this file is running
-echo "Checking game version..."
-sleep 0.5 # Adds fake delay to increase the amount of time the text shows
-
 # Sets the filename based on the version selected by the user
 python_file="quatro-tetris-$version.py"
 
 # Detects the exact version of python the user is running and saves it to a variable
 python_version=$($python_command --version 2>&1 | cut -d' ' -f2)
-
-# Clears the screen because the process was finished
-clear
-
-# Creates a temporary file to store output data
-tmpfile=$(mktemp)
 
 # Runs the game
 if [ -f "$python_file" ]; then
@@ -77,25 +55,40 @@ if [ -f "$python_file" ]; then
     sleep 1
     clear
     # Gets the output given when the game exits
-    $python_command "$python_file" >(tee /dev/tty) 2> "$tmpfile"
+    output=$($python_command "$python_file" 2>&1)
     # Checks the exit code given by the game
     exit_code=$?
     if [ $exit_code -ne 0 ]; then # Checks if the exit was due to an error
         # If the exit was due to an error, the following error code is given
-        clear
-        echo "Error 0000"
-        echo "----------------------"
-        echo "A unexpected error occured. Please try again. If the issue persists, please contact the developer."
-        echo ""
-        echo "More Info"
-        echo "----------------------"
-        echo "Game Version: $version"
-        echo "Python Version: $python_version"
-        echo ""
-        echo "Python Output"
-        echo "----------------------"
-        cat "$tmpfile"
-        exit 1
+        if [[ $output =~ "SyntaxError" ]]; then
+            echo "Error 0005"
+            echo "----------------------"
+            echo "A syntax error in the game code has occured. Please try again. If the issue presists, please contact the developer."
+            echo ""
+            echo "More Info"
+            echo "----------------------"
+            echo "Game Version: $version"
+            echo "Python Version: $python_version"
+            echo ""
+            echo "Python Output"
+            echo "----------------------"
+            echo "$output"
+        else
+            clear
+            echo "Error 0000"
+            echo "----------------------"
+            echo "A unexpected error in the game code has occured. Please try again. If the issue persists, please contact the developer."
+            echo ""
+            echo "More Info"
+            echo "----------------------"
+            echo "Game Version: $version"
+            echo "Python Version: $python_version"
+            echo ""
+            echo "Python Output"
+            echo "----------------------"
+            echo "$output"
+            exit 1
+        fi
     fi
     sleep 1
     clear
@@ -104,8 +97,6 @@ if [ -f "$python_file" ]; then
     echo "Thanks for playing"
     echo "Give feedback on Twitter or Instagram by mentioning @zcraftelite"
     echo ""
-    rm "$tmpfile"
-    exit 1
 else
     clear
     echo "Error 0004"
@@ -114,6 +105,3 @@ else
     echo ""
     exit 1
 fi
-
-# Clears the screen because the process was finished
-clear
