Quatro Tetris - Updated Executable - Developing update command arugment

diff --git a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
--- a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
+++ b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
@@ -30,6 +30,36 @@ if [[ "${@:1:9}" =~ "--debug" ]]; then
     clear
 fi
 
+## [--update] Command
+if [[ "${@:1:9}" =~ "--update" ]]; then
+    debug="y"
+    # Prompt the user for their password using a graphical popup
+    password=$(zenity --password --title="Update Application" --timeout=10)
+
+    # Check if the password was entered successfully
+    if [[ $? -eq 0 ]]; then
+        # Run the script with sudo permissions
+        echo "$password" | sudo -S curl -LJ -o /bin/quatro-tetris \
+        https://raw.githubusercontent.com/zcraftelite9495/codingstuffs/main/Python/Personal%20Project%202024/Quatro-Tetris/quatro-tetris
+        
+        # Download the codingstuffs repository
+        git clone https://github.com/zcraftelite9495/codingstuffs.git
+
+        # Copy the Quatro-Tetris folder to the desired destination
+        cp -R codingstuffs/Python/Personal\ Project\ 2024/Quatro-Tetris/* /Games/Quatro\ Tetris
+
+        # Clean up temporary files
+        rm -rf codingstuffs
+
+        echo "Update has been installed :3"
+        exit 0
+    else
+        echo "You need to enter your password in order to update the file, please rerun the command and enter your password"
+        exit 1
+    fi
+    clear
+fi
+
 ## Main Executable File
 
 # Clears the screen to prepare for game run
