Quatro Tetris - Updated Executable - Added Confirmation for Python Command Autodetect, Added Way To Set Custom Python Command

diff --git a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
--- a/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
+++ b/Python/Personal Project 2024/Quatro-Tetris/quatro-tetris
@@ -1,33 +1,65 @@
 #!/bin/bash
 
+## Variable Resets
+python_command=""
+
+## [--help] Command
+if [ $1 = "-h" || $1 = "--help" ]
+    echo "Quatro Tetris Help"
+    echo "-----------------------------------"
+    echo "Command Operators"
+    echo "-h or --help           | Shows this menu"
+    echo "--py-command [command] | Disables the automatic detection of your Python Command and sets the Python Command value"
+    echo ""
+    echo "-----------------------------------"
+    exit 1
+fi
+
+## [--py-command] Command
+if [ $1 = "--py-command" ]; then
+    python_command="$2"
+    echo "Python Command was set to $python_command"
+fi
+
 # Clears the screen to prepare for game run
 clear
 
 # Tells the user what part of this file is running
 echo "Checking Python Version..."
+sleep 1 # Adds fake delay so text displays longer
 
-# Detects the type of python command you have installed on your system
-if command -v python &>/dev/null; then # Checks to see if you use 'python'
-    python_command="python" # If you use 'python', sets the python command to 'python'
-elif command -v python3 &>/dev/null; then # Checks to see if you use 'python3'
-    python_command="python3" # If you use 'python3', sets the python command to 'python3'
-elif command -v py &>/dev/null; then # Checks to see if you use 'py'
-    # Spits out an error stating that the 'py' command is not compatible with this script
-    echo "Error 0001"
-    echo "----------------------"
-    echo "It appears as if you are using the 'py' command only as your python interpreter. Quatro Tetris is unable to run using the 'py' interpreter. Please install 'python' or 'python3'."
+if [ $python_command = "" ]
+    # Detects the type of python command you have installed on your system
+    if command -v python &>/dev/null; then # Checks to see if you use 'python'
+        python_command="python" # If you use 'python', sets the python command to 'python'
+    elif command -v python3 &>/dev/null; then # Checks to see if you use 'python3'
+        python_command="python3" # If you use 'python3', sets the python command to 'python3'
+    elif command -v py &>/dev/null; then # Checks to see if you use 'py'
+        # Spits out an error stating that the 'py' command is not compatible with this script
+        echo "Error 0001"
+        echo "----------------------"
+        echo "It appears as if you are using the 'py' command only as your python interpreter. Quatro Tetris is unable to run using the 'py' interpreter. Please install 'python' or 'python3'."
+        exit 1
+    elif command -v python2 &>/dev/null; then # Checks to see if you only have 'python2' installed
+        # Spits out an error stating that Quatro Tetris cannot be run with Python 2
+        echo "Error 0002"
+        echo "----------------------"
+        echo "It appears that you do not have a valid Python 3 command interpreter. Quatro Tetris is not able to be ran via Python 2. Please install a Python 3 Interpreter and try again."
+        exit 1
+    else
+        # Spits out an error stating the Quatro Tetris cannot be ran without Python
+        echo "Error 0003"
+        echo "----------------------"
+        echo "It appears that you do not have a valid Python 3 command interpreter. Quatro Tetris cannot be run without Python 3. Please install a Python 3 Interpreter and try again."
+    fi
+fi
+
+# Prompts the user to make sure the system detected the correct python prefix
+clear
+read -p "Quatro Tetris has detected you use the '$python_command' prefix, is this correct? (y/n): " confirmation_1
+if [ $confirmation_1 = "n" ]; then
+    echo "Try changing your configuration and try again. Or use --py-command and then your python command."
     exit 1
-elif command -v python2 &>/dev/null; then # Checks to see if you only have 'python2' installed
-    # Spits out an error stating that Quatro Tetris cannot be run with Python 2
-    echo "Error 0002"
-    echo "----------------------"
-    echo "It appears that you do not have a valid Python 3 command interpreter. Quatro Tetris is not able to be ran via Python 2. Please install a Python 3 Interpreter and try again."
-    exit 1
-else
-    # Spits out an error stating the Quatro Tetris cannot be ran without Python
-    echo "Error 0003"
-    echo "----------------------"
-    echo "It appears that you do not have a valid Python 3 command interpreter. Quatro Tetris cannot be run without Python 3. Please install a Python 3 Interpreter and try again."
 fi
 
 # Clears the screen because the process was finished
